# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to deploy Python Website App Only
# ------------------------------------------------------------------------------------------------------------------------
# You need to set up secrets in the GitHub Secrets Repository before running these workflows.
#   See readme.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: deploy.website
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
          - info
          - warning
          - debug 

jobs:
# ------------------------------------------------------------------------------------------------------------------------
  deploy-dev:
    name: Deploy Website
    uses: ./.github/workflows/template-deploy-python-website.yml
    secrets: inherit
    with:
      envCode: 'dev'
      deployDirectory: './app/backend' 
      
  update-search-dev:
    name: Update Search Index
    needs: deploy-dev
    uses: ./.github/workflows/template-update-search.yml
    secrets: inherit
    with:
      envCode: 'dev'
    