# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to deploy Azure Resources and Website App
# ------------------------------------------------------------------------------------------------------------------------
# You need to set up secrets in the GitHub Secrets Repository before running these workflows.
#   See readme.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: deploy.infra.and.website
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
          - info
          - warning
          - debug 
      DEPLOY_DEV:
        required: true
        type: string
        default: 'true'
      DEPLOY_QA:
        required: true
        type: string
        default: 'false'
      DEPLOY_PROD:
        required: true
        type: string
        default: 'false'
      
jobs:
  infra-web-deploy:
    name: IW
    uses: ./.github/workflows/template-infra-website.yml
    secrets: inherit
    with:
      deployDev: ${{ inputs.DEPLOY_DEV }}
      deployQA: ${{ inputs.DEPLOY_QA }}
      deployProd: ${{ inputs.DEPLOY_PROD }}
