# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to deploy Azure Resources and Website App
# ------------------------------------------------------------------------------------------------------------------------
# You need to set up secrets in the GitHub Secrets Repository before running these workflows.
#   See readme.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: deploy.infra.and.website
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
          - info
          - warning
          - debug 

jobs:
# ------------------------------------------------------------------------------------------------------------------------
  # scan-code:
  #   name: Scan Source Code
  #   uses: ./.github/workflows/template-scan-code.yml

# ------------------------------------------------------------------------------------------------------------------------
  infra-web-deploy:
    name: Infra Web Deploy
    uses: ./.github/workflows/template-infra-website.yml
    secrets: inherit
    with:
      deployDev: ${{ vars.DEPLOY_DEV }}
      deployQA: ${{ vars.DEPLOY_QA }}
      deployProd: ${{ vars.DEPLOY_PROD }}
